insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Lettuce - Sea / Sea Asparagus', 17, 3.05);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Bread - Frozen Basket Variety', 4, 13.95);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Wine - Trimbach Pinot Blanc', 7, 14.43);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Cinnamon - Stick', 20, 13.9);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Mix - Cappucino Cocktail', 9, 12.4);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Rye Special Old', 14, 8.51);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Crab Brie In Phyllo', 13, 12.54);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Yeast Dry - Fleischman', 8, 9.96);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Wine - Two Oceans Sauvignon', 4, 2.3);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Breadfruit', 17, 4.47);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Calypso - Lemonade', 13, 15.18);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Peas Snow', 14, 11.52);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Transfer Sheets', 2, 2.2);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Parsley Italian - Fresh', 16, 14.09);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Ice Cream Bar - Rolo Cone', 17, 9.64);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Truffle Cups - White Paper', 19, 1.19);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Wine - Taylors Reserve', 17, 2.89);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Table Cloth 53x69 White', 20, 17.1);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Chutney Sauce - Mango', 17, 13.27);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Huck White Towels', 17, 5.88);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Carbonated Water - Wildberry', 13, 2.11);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Vinegar - Champagne', 19, 12.37);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Pepper - Green Thai', 10, 11.45);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Cheese - Comte', 20, 8.2);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Turkey - Ground. Lean', 2, 14.98);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Eggplant - Asian', 16, 12.95);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Tray - 16in Rnd Blk', 9, 9.56);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Chickensplit Half', 10, 9.79);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Venison - Ground', 9, 5.0);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Ostrich - Fan Fillet', 5, 4.79);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Cinnamon Buns Sticky', 12, 14.71);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Capers - Pickled', 16, 9.92);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Sponge Cake Mix - Vanilla', 19, 3.9);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Fudge - Cream Fudge', 20, 13.23);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Hersey Shakes', 5, 6.33);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Fish - Artic Char, Cold Smoked', 4, 14.08);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Pur Source', 2, 11.71);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Soup - Campbells Beef Stew', 15, 15.2);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Snapple Lemon Tea', 4, 17.73);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Celery', 18, 9.26);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Chocolate - Feathers', 4, 16.27);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Butter Balls Salted', 17, 4.19);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Butter Balls Salted', 19, 19.45);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Soup Campbells Turkey Veg.', 2, 13.13);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Cherries - Fresh', 1, 2.73);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Pork Ham Prager', 7, 18.55);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Stock - Beef, Brown', 3, 18.48);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('English Muffin', 1, 19.37);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Quail - Whole, Bone - In', 19, 15.61);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Pasta - Fusili Tri - Coloured', 15, 3.57);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Soup - Campbells, Beef Barley', 12, 3.06);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Muffin - Mix - Bran And Maple 15l', 13, 9.29);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Zucchini - Yellow', 18, 2.81);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Beer - Sleemans Cream Ale', 5, 12.47);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Beer - Blue', 12, 4.93);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Beef - Salted', 13, 4.83);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Onions - Cooking', 10, 16.7);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Apricots Fresh', 18, 6.1);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Wakami Seaweed', 18, 19.39);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Carbonated Water - Blackcherry', 6, 5.12);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Sprite, Diet - 355ml', 8, 17.72);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Seaweed Green Sheets', 7, 5.17);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Tequila - Sauza Silver', 5, 4.41);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Bag - Regular Kraft 20 Lb', 4, 15.91);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Bread - Italian Roll With Herbs', 7, 7.88);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Corn - Cream, Canned', 19, 15.89);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Squeeze Bottle', 4, 9.96);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Turkey - Oven Roast Breast', 7, 7.18);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Truffle Shells - Semi - Sweet', 14, 3.42);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Pork - Ground', 13, 5.48);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Pastry - Plain Baked Croissant', 6, 1.11);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Rolled Oats', 10, 2.55);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Sandwich Wrap', 17, 16.57);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Trueblue - Blueberry', 12, 1.76);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Water - Aquafina Vitamin', 16, 9.98);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Fireball Whisky', 7, 4.84);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Lettuce - Romaine', 10, 10.92);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Juice - Apple, 341 Ml', 7, 6.15);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Pectin', 2, 17.91);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Cheese - Blue', 19, 18.03);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Pasta - Canelloni, Single Serve', 5, 15.44);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Cheese - Montery Jack', 16, 16.12);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Taro Root', 16, 10.73);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Tomatoes Tear Drop Yellow', 16, 9.76);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Nut - Pine Nuts, Whole', 16, 14.3);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Lid Coffee Cup 8oz Blk', 8, 5.0);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Appetizer - Cheese Bites', 8, 8.72);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Wine - White, Pelee Island', 16, 14.56);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Sauce Bbq Smokey', 7, 3.64);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Hot Choc Vending', 9, 13.93);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Cardamon Seed / Pod', 9, 9.08);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Bar Bran Honey Nut', 14, 13.07);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Irish Cream - Butterscotch', 3, 14.98);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Juice - Grapefruit, 341 Ml', 10, 12.94);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Squash - Butternut', 15, 1.97);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Vegetable - Base', 4, 16.02);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Soup - Campbells Mushroom', 15, 8.05);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Pastry - Banana Tea Loaf', 9, 7.24);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Pork - Ground', 19, 5.18);
insert into produtos (descricaoProduto, qtdeProduto, precoProduto) values ('Cheese - Manchego, Spanish', 14, 5.16);
